spring:
  application:
    name: cardefectscan
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        order_by.default_null_ordering: last
        format_sql: true
        default_schema: public
    open-in-view: false
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/cardefectscan
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  #  data:
  #    redis:
  #      host: ${REDIS_HOST:localhost}
  #      port: ${REDIS_PORT:6379}
  mustache:
    check-template-location: false

  main:
    web-application-type: servlet

management:
  endpoint:
    health:
      probes:
        enabled: true

auth:
  refresh-lifespan: ${REFRESH_LIFESPAN:604800}
  jwt:
    lifespan: ${JWT_LIFESPAN:120}
    private-key: ${JWT_PRIVATE_KEY}