auth:
  refresh-lifespan: 6000
  jwt:
    lifespan: 6000
    private-key: FJBXvKdzYl0ZlIxC6oTO2HTnitxjdxXX9v5gLG4hYRIbSY3YBtVmWYMRHYmYTguB
  cookies:
    is-http-only: false
    max-age: 604800
    is-secure: false
    domain: localhost

minio:
  endpoint: http://localhost:9000
  access-key: ${MINIO_ROOT_USER}
  secret-key: ${MINIO_ROOT_PASSWORD}
  put-link-expiration: 6000