openapi: 3.0.2
servers:
  - url: http://localhost:8080/api/v1
  - url: https://localhost/backend/api/v1
info:
  description: CarDefectScan API
  version: 0.1.0
  title: CarDefectScan - OpenAPI 3.0
tags:
  - name: Auth
    description: Operations with user account
  - name: Images
    description: Operations with images
  - name: Generations
    description: Operations with processed (or currently being in process) images

paths:
  /auth/signup:
    post:
      tags:
        - Auth
      summary: User Sign Up
      description: Sign Up user and sets JWT and refresh token in cookies
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignupRequest'
      responses:
        "200":
          description: Successful signup, tokens set in cookies
          headers:
            Set-Cookie:
              description: "HttpOnly Secure cookies with access and refresh tokens"
              schema:
                type: string
        "401":
          description: Unauthorized
        "400":
          description: Non unique username or non appropriate password
  /auth/login:
    post:
      tags:
        - Auth
      summary: User login
      description: Authenticates user and sets JWT and refresh token in cookies
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        "200":
          description: Successful login, tokens set in cookies
          headers:
            Set-Cookie:
              description: "HttpOnly Secure cookies with access and refresh tokens"
              schema:
                type: string
        "401":
          description: Unauthorized - wrong email or password
  /auth/refresh:
    post:
      tags:
        - Auth
      summary: Refresh access token
      description: Uses refresh token from cookie to generate a new access token
      responses:
        "200":
          description: New access token issued, set in cookie
          headers:
            Set-Cookie:
              description: "HttpOnly Secure cookie with new access token"
              schema:
                type: string
        "401":
          description: Invalid or expired refresh token
  /auth/logout:
    post:
      tags:
        - Auth
      summary: Logout user
      description: Revokes refresh token and clears cookies
      responses:
        "200":
          description: Logout successful, cookies cleared
          headers:
            Set-Cookie:
              description: "Clears authentication cookies"
              schema:
                type: string
        "401":
          description: Unauthorized

components:
  schemas:
    SignupRequest:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
    LoginRequest:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
    RefreshRequest:
      type: object
      properties:
        refresh_token:
          type: string